<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link rel="stylesheet" type="text/css" href="top-nav-style.css" />
<link rel="stylesheet" type="text/css" href="bottom-nav-style.css" />
<style>
*{
box-sizing:border-box;
}
p{font-size:85%;
}
.container{
width:90%;
margin:auto;
position:absolute;
top:13%;
left:5%;
}
.container h2{
margin:0px;
padding:0px;
color:#463674;
}
.container p{
padding:0px;
margin:0px;
color:#463674;
text-align:justify;
}


</style>
</head>

<body>
<?php 
include 'top-nav.php';
?>
<div class="col-12">

<div class="container">

<h4>General</h4>
<p>This Web site is owned, operated, and maintained by AL SHOLA Transport Co. LLC and its affiliates. Entering into this or any other AL SHOLA site indicates that you have reviewed this AL SHOLA Web Site Terms and Conditions and have agreed to be bound by them. AL SHOLA may change and modify the Terms and Conditions at any time, and from time to time by updating the contents of this page. You, therefore, are requested to visit this page and check the latest Terms and Conditions.
Access to use of Information
Access to any AL SHOLA Web site is limited to viewing the linked Web pages solely to access the information provided by AL SHOLA at its Web sites. Any access or attempt to access other areas of the AL SHOLA computer system or other information contained on the system for any purposes is strictly prohibited.</p>
<h4>Copyright</h4>
<p>All materials, such as documents, text, images, and software, on this Web site are protected by copyright laws and other applicable laws of each country throughout the world, and treaty provisions. Except for personal, non-commercial internal use, you are prohibited to use (including, without limitation, coping, modifying reproducing in whole or in part, uploading, transmitting, distributing, licensing, selling, and publishing) any of the materials, without obtaining AL SHOLA's prior written permission.</p>
<h4>Information Collection</h4>
<p>Personal information, i.e. name, title, company, address, phone number, e-mail address, and other relevant data is not required to access our site. The personal information we do collect is used only to process a request for information or for marketing our products or services. We do not sell, rent or transmit personal information to other organizations. Our web server collects the domain names, like AL SHOLA.co.in, of visitors to our site. This information is aggregated to measure number of visits, average time spent on the site, pages viewed, and other relevant statistics. This information is collected to measure site usage. AL SHOLA’s site may contain links to other non-AL SHOLA sites; however, we are not responsible for the content or the privacy practices employed by other sites.</p>
<h4>Cookies</h4>
<p>AL SHOLA uses cookies only to manage User ID's and make user interaction with our Web sites more efficient. It is the express policy of AL SHOLA that data generated by cookies and related databases will be used for internal purposes only (e.g., to improve the site and site-related services for users). The data compiled via cookies and related databases are considered confidential and will not be sold to entities outside of the organization under any circumstances. </p>
</div>

</div>

<?php
include 'bottom-nav.php';
?>

</body>
</html>
